FROM node:18-alpine AS builder

WORKDIR /app
COPY . .

RUN npm cache clean --force
RUN npm install --legacy-peer-deps
RUN npm run build -- --configuration=production

# Ensuite la partie nginx
FROM nginx:stable-alpine
COPY --from=builder /app/dist/pi /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
